export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForLightBackground: "#fff6d9",
  colorForDarkBackground: "#ffeead",
  panelBackgroundColorDanger: "#f75531",
  panelBackgroundColor: "#88aa4d",
  backgroundColorBlue: "#d8ecfe",
  backgroundColorGray: "#f7f7f7",
  colorForNewIcon: "#ffb334",
  colorForSoftIcon: "#7fc92e",
  colorForButton: "#ff732B",
  colorForButtonHover: "#F35714",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  headerHeight: "80px",
  pageWidth: "1280px"
};
